root: /home/jongphago/project/ultralytics/datasets
name: aihub/subset/by_scenario
source:
  train:
    [
      [
        "image": "aihub/2.Validation/frames/시나리오19",
        "label": "aihub/2.Validation/converts/시나리오19",
      ],
      [
        "image": "aihub/2.Validation/frames/시나리오42",
        "label": "aihub/2.Validation/converts/시나리오42",
      ],
    ]
  validation:
    [
      [
        "image": "aihub/2.Validation/frames/시나리오43",
        "label": "aihub/2.Validation/converts/시나리오43",
      ],
    ]
target:
  train: train
  validation: validation
